chore(ci): disable automatic changelog and release
Signed-off-by: Anton Engelhardt <antoncengelhardt@icloud.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -177,154 +177,154 @@ jobs:
         with:
           args: rollout restart deployment wasm-oidc-plugin -n wasm-oidc-plugin
 
-  changelog-and-release:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}
+  # changelog-and-release:
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: write
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}
 
-      - name: Exit if latest commit is release commit (to avoid infinite loop)
-        run: |
-          if git log -1 --pretty=%B | grep -q "chore(release): prepare for"; then
-            echo "Latest commit is a release commit, exiting..."
-            echo "EXIT=1" >> $GITHUB_ENV
-            exit 0
-          fi
+  #     - name: Exit if latest commit is release commit (to avoid infinite loop)
+  #       run: |
+  #         if git log -1 --pretty=%B | grep -q "chore(release): prepare for"; then
+  #           echo "Latest commit is a release commit, exiting..."
+  #           echo "EXIT=1" >> $GITHUB_ENV
+  #           exit 0
+  #         fi
 
-      - name: Get most recent merged PR and calculate the next tag
-        if: env.EXIT != '1'
-        id: get_pr
-        run: |
-          MOST_RECENTLY_MERGED_PR=$(curl -s -H 'Accept: application/vnd.github.v3+json' "https://api.github.com/repos/antonengelhardt/wasm-oidc-plugin/pulls?state=closed" | \
-          jq '[.[] | select(.merged_at != null)] | max_by(.merged_at)')
-          PR_NUMBER=$(echo $MOST_RECENTLY_MERGED_PR | jq -r '.number')
+  #     - name: Get most recent merged PR and calculate the next tag
+  #       if: env.EXIT != '1'
+  #       id: get_pr
+  #       run: |
+  #         MOST_RECENTLY_MERGED_PR=$(curl -s -H 'Accept: application/vnd.github.v3+json' "https://api.github.com/repos/antonengelhardt/wasm-oidc-plugin/pulls?state=closed" | \
+  #         jq '[.[] | select(.merged_at != null)] | max_by(.merged_at)')
+  #         PR_NUMBER=$(echo $MOST_RECENTLY_MERGED_PR | jq -r '.number')
 
-          LABELS=$(curl -s -H 'Accept: application/vnd.github.v3+json' "https://api.github.com/repos/antonengelhardt/wasm-oidc-plugin/issues/$PR_NUMBER" | jq -r '.labels[].name')
+  #         LABELS=$(curl -s -H 'Accept: application/vnd.github.v3+json' "https://api.github.com/repos/antonengelhardt/wasm-oidc-plugin/issues/$PR_NUMBER" | jq -r '.labels[].name')
 
-          # Set SEMVER_BUMP based on the presence of labels
-          if [[ $LABELS == *"major"* ]]; then
-            SEMVER_BUMP="major"
-          elif [[ $LABELS == *"minor"* ]]; then
-            SEMVER_BUMP="minor"
-          elif [[ $LABELS == *"bug"* ]]; then
-            SEMVER_BUMP="patch"
-          elif [[ $LABELS == *"patch"* ]]; then
-            SEMVER_BUMP="patch"
-          else
-            SEMVER_BUMP="none"
-            echo "EXIT=1" >> $GITHUB_ENV
-            exit 0 # exit if no labels are found, which means no version bump is required
-          fi
+  #         # Set SEMVER_BUMP based on the presence of labels
+  #         if [[ $LABELS == *"major"* ]]; then
+  #           SEMVER_BUMP="major"
+  #         elif [[ $LABELS == *"minor"* ]]; then
+  #           SEMVER_BUMP="minor"
+  #         elif [[ $LABELS == *"bug"* ]]; then
+  #           SEMVER_BUMP="patch"
+  #         elif [[ $LABELS == *"patch"* ]]; then
+  #           SEMVER_BUMP="patch"
+  #         else
+  #           SEMVER_BUMP="none"
+  #           echo "EXIT=1" >> $GITHUB_ENV
+  #           exit 0 # exit if no labels are found, which means no version bump is required
+  #         fi
 
-          # Output the SEMVER_BUMP value
-          echo "SEMVER_BUMP is set to: $SEMVER_BUMP"
+  #         # Output the SEMVER_BUMP value
+  #         echo "SEMVER_BUMP is set to: $SEMVER_BUMP"
 
-          # LATEST_TAG=$(git describe --tags --abbrev=0)
-          LATEST_TAG=$(curl "https://api.github.com/repos/antonengelhardt/wasm-oidc-plugin/tags" | jq -r '.[0].name')
+  #         # LATEST_TAG=$(git describe --tags --abbrev=0)
+  #         LATEST_TAG=$(curl "https://api.github.com/repos/antonengelhardt/wasm-oidc-plugin/tags" | jq -r '.[0].name')
 
-          # Function to bump version numbers
-          bump_version() {
-              local IFS=.
-              local -a parts=($1)
+  #         # Function to bump version numbers
+  #         bump_version() {
+  #             local IFS=.
+  #             local -a parts=($1)
 
-              case "$2" in
-                  major)
-                      ((parts[0]++))
-                      parts[1]=0
-                      parts[2]=0
-                      ;;
-                  minor)
-                      ((parts[1]++))
-                      parts[2]=0
-                      ;;
-                  patch)
-                      ((parts[2]++))
-                      ;;
-                  *)
-                      echo "Error: Unknown version bump type '$2'"
-                      exit 1
-                      ;;
-              esac
+  #             case "$2" in
+  #                 major)
+  #                     ((parts[0]++))
+  #                     parts[1]=0
+  #                     parts[2]=0
+  #                     ;;
+  #                 minor)
+  #                     ((parts[1]++))
+  #                     parts[2]=0
+  #                     ;;
+  #                 patch)
+  #                     ((parts[2]++))
+  #                     ;;
+  #                 *)
+  #                     echo "Error: Unknown version bump type '$2'"
+  #                     exit 1
+  #                     ;;
+  #             esac
 
-              echo "${parts[0]}.${parts[1]}.${parts[2]}"
-          }
+  #             echo "${parts[0]}.${parts[1]}.${parts[2]}"
+  #         }
 
-          current_version=${LATEST_TAG:1}
+  #         current_version=${LATEST_TAG:1}
 
-          # Bump the version based on the SEMVER_BUMP
-          new_version=$(bump_version "$current_version" "$SEMVER_BUMP")
-          echo "VERSION=$new_version" >> $GITHUB_ENV
+  #         # Bump the version based on the SEMVER_BUMP
+  #         new_version=$(bump_version "$current_version" "$SEMVER_BUMP")
+  #         echo "VERSION=$new_version" >> $GITHUB_ENV
 
-          # Append 'v' prefix if required to maintain the same version format
-          NEW_TAG="v$new_version"
-          echo "New tag after bump is: $NEW_TAG"
-          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
+  #         # Append 'v' prefix if required to maintain the same version format
+  #         NEW_TAG="v$new_version"
+  #         echo "New tag after bump is: $NEW_TAG"
+  #         echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
 
-      - name: Bump Version on Cargo.toml
-        if: env.EXIT != '1'
-        run: sed -i "s/^version = \".*\"/version = \"${{ env.VERSION }}\"/" Cargo.toml
+  #     - name: Bump Version on Cargo.toml
+  #       if: env.EXIT != '1'
+  #       run: sed -i "s/^version = \".*\"/version = \"${{ env.VERSION }}\"/" Cargo.toml
 
-      - name: Git Cliff
-        if: env.EXIT != '1'
-        id: generate_changelog
-        uses: orhun/git-cliff-action@v3
-        with:
-          config: cliff.toml
-          args: -l --prepend CHANGELOG.md --strip header
-        env:
-          GITHUB_REPO: ${{ github.repository }}
+  #     - name: Git Cliff
+  #       if: env.EXIT != '1'
+  #       id: generate_changelog
+  #       uses: orhun/git-cliff-action@v3
+  #       with:
+  #         config: cliff.toml
+  #         args: -l --prepend CHANGELOG.md --strip header
+  #       env:
+  #         GITHUB_REPO: ${{ github.repository }}
 
-      - name: sed [unreleased] with new version in CHANGELOG.md
-        if: env.EXIT != '1'
-        run: sed -i "s/\[unreleased\]/${{ env.NEW_TAG }}/" CHANGELOG.md
+  #     - name: sed [unreleased] with new version in CHANGELOG.md
+  #       if: env.EXIT != '1'
+  #       run: sed -i "s/\[unreleased\]/${{ env.NEW_TAG }}/" CHANGELOG.md
 
-      - name: sed [unreleased] with new version in RELEASE_NOTES.md
-        if: env.EXIT != '1'
-        run: |
-          cat ${{ steps.generate_changelog.outputs.changelog }} > RELEASE_NOTES.md
-          sed -i "s/\[unreleased\]/${{ env.NEW_TAG }}/" RELEASE_NOTES.md
+  #     - name: sed [unreleased] with new version in RELEASE_NOTES.md
+  #       if: env.EXIT != '1'
+  #       run: |
+  #         cat ${{ steps.generate_changelog.outputs.changelog }} > RELEASE_NOTES.md
+  #         sed -i "s/\[unreleased\]/${{ env.NEW_TAG }}/" RELEASE_NOTES.md
 
-      - name: Print Changelog
-        if: env.EXIT != '1'
-        run: cat ${{ steps.generate_changelog.outputs.changelog }} && echo "##" && cat CHANGELOG.md
+  #     - name: Print Changelog
+  #       if: env.EXIT != '1'
+  #       run: cat ${{ steps.generate_changelog.outputs.changelog }} && echo "##" && cat CHANGELOG.md
 
-      - name: Commit Version and CHANGELOG.md
-        if: env.EXIT != '1'
-        run: |
-          git checkout origin/main
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          set +e
-          git add Cargo.toml CHANGELOG.md
-          cargo check
-          git add Cargo.lock
-          git commit -m "chore(release): prepare for ${{ env.NEW_TAG }}"
-          git push origin HEAD:main
+  #     - name: Commit Version and CHANGELOG.md
+  #       if: env.EXIT != '1'
+  #       run: |
+  #         git checkout origin/main
+  #         git config user.name "github-actions[bot]"
+  #         git config user.email "github-actions[bot]@users.noreply.github.com"
+  #         set +e
+  #         git add Cargo.toml CHANGELOG.md
+  #         cargo check
+  #         git add Cargo.lock
+  #         git commit -m "chore(release): prepare for ${{ env.NEW_TAG }}"
+  #         git push origin HEAD:main
 
-      - name: Create a tag on main
-        if: env.EXIT != '1'
-        run: |
-          git checkout origin/main
+  #     - name: Create a tag on main
+  #       if: env.EXIT != '1'
+  #       run: |
+  #         git checkout origin/main
 
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git config user.name "github-actions[bot]"
+  #         git config user.email "github-actions[bot]@users.noreply.github.com"
+  #         git config user.name "github-actions[bot]"
 
-          git tag ${{ env.NEW_TAG }}
+  #         git tag ${{ env.NEW_TAG }}
 
-          git push origin ${{ env.NEW_TAG }}
+  #         git push origin ${{ env.NEW_TAG }}
 
-      - name: Create Release
-        uses: actions/create-release@v1
-        if: env.EXIT != '1'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ env.NEW_TAG }}
-          release_name: ${{ env.NEW_TAG }}
-          body_path: RELEASE_NOTES.md
-          draft: false
-          prerelease: false
+  #     - name: Create Release
+  #       uses: actions/create-release@v1
+  #       if: env.EXIT != '1'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       with:
+  #         tag_name: ${{ env.NEW_TAG }}
+  #         release_name: ${{ env.NEW_TAG }}
+  #         body_path: RELEASE_NOTES.md
+  #         draft: false
+  #         prerelease: false
